target 'DemoApp' do
  platform :ios, '11.0'
  use_frameworks!

  # Pods for DemoApp
  pod 'Mux-Stats-Google-IMA-Kaltura', :path => '../', :testspecs => ['Tests'] 
# Remove next line before release
  pod 'Mux-Stats-Kaltura', :path => '../../mux-stats-sdk-kaltura-ios'
  pod 'PlayKit_IMA'
end

# target 'DemoAppTvOS' do
  # platform :tvos, '11.0'
  # use_frameworks!
  
  # pod 'Mux-Stats-Google-IMA-Kaltura', :path => '../'
  # pod 'PlayKit_IMA'
# end

